apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test-pod
  name: multitool-test
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool
      ports:
        - containerPort: 2280
          name: http-port
        - containerPort: 22443
          name: https-port
      env:
        - name: HTTP_PORT
          value: "2280"
        - name: HTTPS_PORT
          value: "22443"