apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: nginx
  ports:
    - name: nginx-service-port
      protocol: TCP
      port: 81
      targetPort: 80
    - name: multitool-service-port
      protocol: TCP
      port: 82
      targetPort: 1180