---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.112.75
      ansible_user: centos
vector:
  hosts:
    vector-01:
      ansible_host: 158.160.103.229
      ansible_user: centos
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.123.72
      ansible_user: centos