apiVersion: v1
kind: ConfigMap
metadata:
  name: confmap2
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="ru">
    <head>
    <meta charset="UTF-8">
    <title> Это простая страница html</title>
    </head>
    <body>
    Пример еще одной простой страницы для другого задания по Kubernetes
    </body>
    </html>
