apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
  labels:
    app: deploy1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy1
  template:
    metadata:
      labels:
        app: deploy1
    spec:
      containers:
      - name: busybox
        image: busybox:1.28
        command: [ 'sh', '-c', 'while true; do sleep 5; date >> /test/test.log; done;' ]
        volumeMounts:
          - name: vol1
            mountPath: /test
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
          - name: vol1
            mountPath: /test
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: pv-claim-1

