apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: busybox
          image: busybox:1.28
          command: [ 'sh', '-c', 'while true; do sleep 5; if nslookup service-nginx; then exit 0; fi; done; exit 1' ]
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80