apiVersion: apps/v1
kind: Deployment
metadata:
  name: programma
  labels:
    app: programma
spec:
  replicas: 3
  selector:
    matchLabels:
      app: programma
  template:
    metadata:
      labels:
        app: programma
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        ports:
          - containerPort: 8080
            name: http-port
        env:
        - name: HTTP_PORT
          value: "8080"
