apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  type: NodePort
  selector:
    app: programma
  ports:
    - name: nginx-service-port
      protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 30001
    - name: multitool-service-port
      protocol: TCP
      port: 9002
      targetPort: 8080
      nodePort: 30002